### ISSUE TITLE
does it support random sample?

### ISSUE THREAD

**Issue by jjhesk** [BoLaMN/loopback-mongo-aggregate-mixin#1]
i found that from [here](https://docs.mongodb.com/v3.2/reference/operator/aggregation/sample/) which doesnt support from this mixin.

**Comment by BoLaMN** [comment]
it should see https://github.com/BoLaMN/loopback-mongo-aggregate-mixin/blob/master/src/query.coffee#L84

so just 

"aggregate": {
  "sample": 5
}
