### ISSUE TITLE
How to use in filter?

### ISSUE THREAD

**Issue by thanhdk** [BoLaMN/loopback-mongo-aggregate-mixin#4]
Hi, I have putted below code on filter of explorer but it always show all object
{ "aggregate": { "group": { "id": "$isCompleted", "count": { "$sum": 1 } } } }
It seem to I have wrong in structure or something like that.
I want to count all object that have field "isCompleted", so do you have any hints?

**Comment by thanhdk** [comment]
I have found that I missing this step -> mixin to enable the aggregation pipeline
But, how to enable to use with model ?

**Comment by BoLaMN** [comment]
add "node_modules/loopback-mongo-aggregate-mixin' to your model-config.json to the meta sources mixin section
add mixins: { "Aggregate": true } to your model 
use /api/modelName/aggregate endpoint 

https://loopback.io/doc/en/lb3/Defining-mixins.html

**Comment by thanhdk** [comment]
yah, I have missed the "/dist" folder, it work right now, thank you very much
